name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: priyanshuvishwakarma273403
          outputs: |
            dist/snake.svg

      - name: Push snake animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b output || git checkout output
          cp dist/snake.svg snake.svg
          git add snake.svg
          git commit -m "update snake animation" || echo "No changes"
          git push origin output
